---
title: "Homework 3"
author: "Mari Sanders"
date: "2024-10-05"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

library(p8105.datasets)
```

# Problem 1 

```{r}
data("ny_noaa") 

view(ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-"))
```

# Problem 2 

```{r}
accel_df <- 
  read_csv("data/nhanes_accel.csv") %>% 
  janitor::clean_names() 

demographic_df <- read_csv("data/nhanes_covar.csv", skip = 4) %>% 
  drop_na() %>% 
  janitor::clean_names() %>%
  filter(age > 21) %>%  
  mutate(sex, sex = as.factor(sex)) %>% 
  mutate(education, education = as.factor(education))

demographic_accel_df <- 
  left_join(demographic_df, accel_df, by = "seqn")
```

```{r}
demographic_accel_df %>% 
  group_by(sex, education) %>%
  summarize(count = n()) %>% 
  knitr::kable()
```

```{r}
demographic_accel_df %>% 
  group_by(sex, age, education) %>% 
  ggplot(aes(x = age, color = sex)) + 
  geom_histogram() + 
  facet_grid(sex ~ education)
```

**Comment on Distribution**

```{r}
demographic_accel_df %>% 
  mutate(total_activity = rowSums(select(., starts_with("min")))) %>% 
  ggplot(aes(x = age, y = total_activity, color = sex)) + 
  geom_point() + 
  facet_grid(sex~education) + geom_smooth() 
```

**Comment on Distribution**

```{r}
demographic_accel_df %>% 
  pivot_longer(
    cols = min1:min1440, 
    values_to = "data",
    names_to = "minute", 
    names_prefix = "min"
  ) %>% ggplot(aes(x = minute, y = data, color = sex)) + geom_point() + facet_grid(~education)
```

# Problem 3 

```{r}
jan_2020 <- read_csv("data/Jan_2020_Citi.csv") %>% 
  mutate(year = 2020) %>% 
  mutate(month = "Jan") %>% 
  relocate(year, month, .before = ride_id)
jan_2024 <- read_csv("data/Jan_2024_Citi.csv") %>% 
  mutate(year = 2024) %>% 
  mutate(month = "Jan") %>% 
  relocate(year, month, .before = ride_id)
july_2020 <- read_csv("data/July_2020_Citi.csv") %>% 
  mutate(year = 2020) %>% 
  mutate(month = "July") %>% 
  relocate(year, month, .before = ride_id)
july_2024 <- read_csv("data/July_2024_Citi.csv") %>% 
  mutate(year = 2024) %>% 
  mutate(month = "July") %>% 
  relocate(year, month, .before = ride_id)

citi_bike_df <- 
  bind_rows(jan_2020, july_2020, jan_2024, july_2024) 
```


```{r}
citi_bike_df %>% 
  group_by(year, month, member_casual) %>% 
  summarize(count = n()) %>%
  knitr::kable()
```

**Comment on Result**

```{r}
citi_bike_df %>% 
  filter(month == "July" & year == "2024") %>% 
  group_by(start_station_name) %>% 
  summarize(count = n()) %>%  arrange(desc(count)) %>% head(5) %>% knitr::kable()
```


```{r}
citi_bike_df %>%
  mutate(weekdays = factor(weekdays, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),ordered = TRUE)) %>% 
  group_by(year, month, weekdays) %>% 
  mutate(median_duration = median(duration)) %>% ggplot(aes(x = weekdays, y = median_duration, fill = as.factor(year))) + geom_bar(stat = "identity", position = "dodge") + facet_grid(~month) + theme(axis.text = element_text(angle = 45, vjust = 1, hjust = 1))
```
